### ISSUE TITLE
[ALL][EPIC] Architecture rework

### ISSUE THREAD

**Issue by djey47** [djey47/cool-updown#49]
Switch to a nodeJS backend and a proper UI framework on client side.

So that the API could be invoked with different clients (own web UI, magic mirror module, mobile app....)

## Planned features/stories:

- Preparing
  - [x]  Rename current repo to cool-updown-legacy
  - [x] Create new mono repo (cool-updown-nxt)
  - [ ] Migrate tasks and features to new repo
- Migrate current 'services' to JSON REST API
  - [ ] Persist state to disk to handle services shutdown or restarts
  - [ ] Implement polling to backend and API will just query the internal state  
  - [ ] DEBUG mode as env variable?
- Create a front-end with Vite (choose framework:  React, Vue ..... ?)
  - [ ] PWA 
- Create a magic mirror 2 module (new github repository)
- Documentation update
  - [ ] GH repo update (description etc)

**Comment by djey47** [comment]
TBC https://github.com/djey47/cool-updown-nxt/issues/1
